// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RS_MessageSystem","status":true,"description":"한글 메시지 시스템 (v0.0.3)","parameters":{"폰트 사이즈":"28","numVisibleRows":"4","gradientColor1":"#FFFFFF","gradientColor2":"#F29661","gradientColor3":"#CC3D3D","텍스트 속도":"0","폰트 최소 크기":"24","폰트 최대 크기":"96","텍스트 시작 X":"256","이름 윈도우 X":"0","이름 윈도우 Y":"0","이름 윈도우 안쪽 여백":"10","큰 페이스칩 OX":"0","큰 페이스칩 OY":"0  \r"}}
];
