// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RS_ArabicMessageSystem","status":false,"description":"right-to-left language support for RMMV <RS_ArabicMessageSystem>","parameters":{"Message Mode":"arabic","Arabic Font":"Simplified Arabic, Times New Roman, Segoe UI"}},
{"name":"RS_PauseGame","status":true,"description":"This plugin allows user to pause the game.","parameters":{"keyCode":"0x50","Pause Image Src":"pause"}}
];
