// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"RS_InputDialog","status":true,"description":"this plugin allows you to display Text Edit Box on the screen.","parameters":{"textBox Width":"488","textBox Height":"36","variable ID":"3","debug":"false","Text":"Please enter the value...","Background Color":"rgba(255, 255, 255, 0.8)","direction":"ltr"}}
];
